version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
      - redis
      - celery
    networks:
      - graphql_network

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - graphql_network

  redis:
    image: redis:7
    networks:
      - graphql_network

  celery:
    build: .
    command: celery -A core.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - graphql_network

  celery-beat:
    build: .
    command: celery -A core.celery beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - celery
      - redis
      - db
    networks:
      - graphql_network

networks:
  graphql_network:

volumes:
  postgres_data:
